# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
          # STI
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    
    - name: shell script to sync the repo and remote directory
      uses: appleboy/ssh-action@master
      with:
        host: 35.232.17.159
        username: revanth
        key: ${{ secrets.HOST_GIT_PRIVATE_KEY }}
        script: |
          if [ cd /home/revanth/rick && ls -Fa | grep -q '.git/' ]
                  if [ cd /home/revanth/rick && git config --get remote.origin.url | grep -q 'workflows-test1' ]
                  then
                          cd /home/revanth/rick && git pull 
                  fi
          else
                  cd /home/revanth/rick && git init
                  cd /home/revanth/rick && git remote add origin git@github.com:revanth-itv/workflows-test1.git
                  cd /home/revanth/rick && git pull origin master
          then
                  echo "done"
          fi
